services:
  #---------------- Backend Service (FastAPI) ----------------#
  - type: web
    name: trip-planner-backend
    env: docker
    repo: https://github.com/pritambhutada5/trip_planner_ai.git
    rootDir: trip_planner_new_repo
    dockerCommand: ./start.sh
    healthCheckPath: /health
    envVars:
      - key: GEMINI_API_KEY
        sync: false # You will set this value in the Render dashboard

  #---------------- Frontend Service (Streamlit) ----------------#
  - type: web
    name: trip-planner-frontend
    env: docker
    repo: https://github.com/pritambhutada5/trip_planner_ai.git
    rootDir: trip_planner_new_repo
    dockerCommand: streamlit run streamlit_app.py --server.port $PORT --server.address 0.0.0.0
    envVars:
      - key: API_URL
        value: https://trip-planner-backend.onrender.com
      # The endpoint path remains the same.
      - key: API_ENDPOINT_PATH
        value: /api/plan-full-trip
